services:
  db:
    image: postgres:16
    restart: always
    container_name: compliment_base
    networks:
      - compliment_net
    # Если база упадет, перезапуск
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
    # путь к файлу с переменными бд 
    env_file:
      - ./docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./baskups:/data
    # порты пробрасываются для внешних подключений, дабы до сервиса можно было достучаться снаружи
    ports:
      - 5433:5432
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8000:8000
    container_name: compliment
    networks:
      - compliment_net
    env_file:
      - ./docker.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    #restart: on-failure
volumes:
  postgres_data:
networks:
  compliment_net:
    driver: bridge